name: Check workspace

on:
  pull_request:
  merge_group:

jobs:
  check-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.0 (22. Sep 2023)

      - name: install python deps
        run: pip3 install toml

      - name: check integrity
        run: >
            python3 .github/scripts/check-workspace.py .
            --exclude
            "substrate/frame/contracts/fixtures/build"
            "substrate/frame/contracts/fixtures/contracts/common"
