name: Rustfmt check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:

jobs:
  quick_check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.77.0-2024-04-10-v20240408
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check
